### ISSUE TITLE
Error in send message!

### ISSUE THREAD

**Issue by 13dev** [gerardojbaez/messenger#1]
Type error: 

` Argument 1 passed to Gerardojbaez\Messenger\Messenger::from() must be an instance of Gerardojbaez\Messenger\Contracts\MessageableInterface, integer given, called in /var/www/html/work/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 217`

Why ? i follow the instructions

**Comment by gerardojbaez** [comment]
You must pass the user instance instead of the id. Remember, your User model should implement the 'Gerardojbaez/Messenger/Contracts/MessageableInterface'.

**Comment by 13dev** [comment]
in model user i have:
use Gerardojbaez\Messenger\Contracts\MessageableInterface;
use Gerardojbaez\Messenger\Traits\Messageable;
class User extends Authenticatable implements MessageableInterface
{
    use Messageable;

i have to do this ? 
Messenger::from(\Auth::user()->id)->to($user2)->message('Hey!')->send();

**Comment by gerardojbaez** [comment]
Your model looks ok. 

Almost, do this:

```php

$user2 = User::find(2));

Messenger::from(\Auth::user())->to($user2)->message('Hey!')->send();
```

You need to pass the user instance, not the id.

**Comment by 13dev** [comment]
Oh Okay, I have one controller
`use Messenger;
use Auth;
use App\User;

class MessagesController extends Controller
{
    public function enviar(){

    	$user2 = User::find(2);
    	$Message = Messenger::from(\Auth::user())->to($user2)->message('Hey!')->send();
    	//dd($Message);
    }
	
}`

but its say 'Trying to get property of non-object' 
Im Logged

**Comment by gerardojbaez** [comment]
I can't replicate the error. Are you sure you're authenticated and that the user with id of 2 exists?

**Comment by 13dev** [comment]
Hey Dude Its fixed! Thanks! nice package men :) ! 
if I find some more error I warn you
+1 star

**Comment by gerardojbaez** [comment]
You're welcome! Thanks!
