### ISSUE TITLE
migrate error fix 

### ISSUE THREAD

**Issue by 13dev** [gerardojbaez/messenger#2]
i dont now but...
if you run `php artisan migrate` you will get this error
` [PDOException]                                                          
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint `
what I did to solve the problem was ..

remove the this of ` create_messages_table` :
```php
$table->foreign('thread_id')->references('id')->on('message_threads')->onDelete('cascade');
$table->foreign('sender_id')->references('id')->on('users')->onDelete('cascade');
```

And put this on `create_message_threads_table` :
```php
Schema::table('messages', function($table) 
{
    $table->foreign('thread_id')->references('id')->on('message_threads')->onDelete('cascade');
    $table->foreign('sender_id')->references('id')->on('users')->onDelete('cascade');
});
```

this solve my problem I hope it helps

**Comment by gerardojbaez** [comment]
And you end up finding another bug! I'm going to check this out now. Thanks!

**Comment by 13dev** [comment]
you are welcome, I just want to help :),  sorry for all this work!

**Comment by gerardojbaez** [comment]
Done! 

Don't worry, I appreciate your help. :-)
