### ISSUE TITLE
Any plans for a L5.3 release

### ISSUE THREAD

**Issue by kiwo12345** [gerardojbaez/messenger#3]
Thanks for sharing this! :)

Do you have any plans for a L5.3 release?

(I have not tested it in L5.3 myself)

**Comment by gerardojbaez** [comment]
You're welcome! :smiley:

I do plan to do a L5.3 release if the current release isn't compatible. I'll let you know.

**Comment by gerardojbaez** [comment]
Messenger is compatible with Laravel 5.3!
